- hosts: mock_host1
  gather_facts: False
  tasks:
  - cidrblock.conn_test.add:
      first: 1
      second: 2
    ignore_errors: True
  
  - cidrblock.conn_test.add:
      first: 1
      second: 10
      third: 5
    ignore_errors: True
  
  - cidrblock.conn_test.add:
      first: 1
      second: 10
    register: result

  - assert:
      that: "{{ result.sum == 11 }}"
  
  - debug: 
      var: result
  
  - cidrblock.conn_test.add:
      first: 1
      second: 10
      third: 10
      fourth: 21
    register: result

  - assert:
      that: "{{ result.sum == 42 }}"
  
  - debug: 
      var: result
